services:
  app:
    image: luismalta/airbnb:latest
    environment:
      - SELENIUM_URL=selenium
    volumes:
      - ./AirbnbScraper:/app
    depends_on:
      - selenium
  
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: '2gb'